### ISSUE TITLE
document how to create and upload the javascript sourcemap

### ISSUE THREAD

**Issue by respectTheCode** [SudoPlz/react-native-bugsnag#1]

**Comment by joshuapinter** [comment]
@SudoPlz is working on this with a Bugsnag open source rep right now actually.

**Comment by SudoPlz** [comment]
We're currently trying to find a way to make this work with @kattrali on https://gitter.im/SudoPlz/react-native-bugsnag

**Comment by SudoPlz** [comment]
Ok all you need to do to to get a readable js stacktrace is [create sourcemaps for your app](http://stackoverflow.com/questions/34715106/how-to-added-sourcemap-in-react-native-for-production), then [upload them to bugsnag](http://docs.bugsnag.com/api/js-source-map-upload/#uploading-source-maps) and then make your project of type `Javascript` in the bugsnag dashboard, (you do that from their Settings screen). I did that and now I get a translated stacktrace I can read.

For now this works well but its not yet fancy, their team is working on it from what I know.
