### ISSUE TITLE
Confusing exception using `setReleaseStage` and `suppressDev`

### ISSUE THREAD

**Issue by mmzoo** [SudoPlz/react-native-bugsnag#13]
Hi, I'm trying to use the new `setReleaseStage` method (iOS) but I'm greeted by an exception.

When using _one of_ the following statements, Bugsnag operates as expected:

``` js
Bugsnag()
Bugsnag({ suppressDevErrors: false })
Bugsnag({ suppressDevErrors: true })
```

But using the following...

``` js
// __DEV__ is true
Bugsnag().setReleaseStage('staging')
```

...leads to the following exception (which stops my application alltogether during boot):

```
Possible Unhandled Promise Rejection (id: 0):
RNBugsnag won't report errors on dev mode, use setSuppressDebug to set suppress to false in order to use it on dev.
Error: RNBugsnag won't report errors on dev mode, use setSuppressDebug to set suppress to false in order to use it on dev.
    at createErrorFromErrorData (http://0.0.0.0:8081/index.ios.bundle?platform=ios&dev=true:4001:11)
    at http://0.0.0.0:8081/index.ios.bundle?platform=ios&dev=true:3952:11
    at MessageQueue.__invokeCallback (http://0.0.0.0:8081/index.ios.bundle?platform=ios&dev=true:3815:10)
    at http://0.0.0.0:8081/index.ios.bundle?platform=ios&dev=true:3686:8
    at guard (http://0.0.0.0:8081/index.ios.bundle?platform=ios&dev=true:3613:1)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://0.0.0.0:8081/index.ios.bundle?platform=ios&dev=true:3685:1)
    at onmessage (http://localhost:8081/debuggerWorker.js:39:56)
```

Now, I realize this is because of [this reject](https://github.com/SudoPlz/react-native-bugsnag/blob/5748cd072d337aabc6801e4940850981c4578547/ios/RNBugsnag/RNBugsnag.m#L26) you're sending. 

But this following line causes the same exception:

``` js
Bugsnag({ suppressDevErrors: false }).setReleaseStage('staging')
```

I did not expect this. I don't want it to swallow exceptions, but I still receive the same reject (which is just a guard to not notifying Bugsnag for real).

So what I'm imagining happens is this (pure speculation):
- Bugsnag gets initialized, but `suppressDevErrors = false` is not immediately propagated to the native `RNBugsnag`
- So `suppressDevErrors` is internally still `true` when `setReleaseStage` is called
- Some exception occurs when calling `setReleaseStage`
- The exception is to be delivered by `RNBugsnag#notify`, which still has `suppressDevErrors` on `true`, so it rejects it.

So I can never know what exception is actually raised.

Is there any way the `reject` could include the `exceptionTitle` and the `exceptionReason` in its warning message? So I could get a hint at what's going wrong internally.

Or am I totally in the woods? :)

Thank you for your time.

**Comment by SudoPlz** [comment]
It seems to me that you nailed it. That has to be exactly whats taking place on the background. I have to test more to be sure though.

**Comment by SudoPlz** [comment]
I believe  the problem was that when the `__DEV__` flag was true, the lib totally ignored the `suppressDevErrors` flag. It has to be fixed after this commit https://github.com/SudoPlz/react-native-bugsnag/commit/2cb20eae68b4f5180ce6f4a305aa70882f63b48d . 
Would you mind giving it another try after pulling the new code (v0.0.9), and then let me know if the problem is gone? 

Thank you!

**Comment by mmzoo** [comment]
Hi!

Using `0.0.9` my app boots properly now with

``` js
Bugsnag({ suppressDevErrors: false }) 
Bugsnag().setReleaseStage('development')  // <- This does not cause a breakdown any more
```

However, exceptions are then not reported to bugsnag.com. Also passing in `staging` or `production`does not make a difference. Once I remove `setReleaseStage`, exceptions are properly reported again throughout my app.

I'm really not sure why that is.

**Comment by SudoPlz** [comment]
I cannot reproduce this unfortunately. 
[Here ](https://docs.bugsnag.com/platforms/ios-objc/configuration-options/#releasestage) is the actual bugsnag documentation that was followed and the code that does that can be found [here](https://github.com/SudoPlz/react-native-bugsnag/blob/master/ios/RNBugsnag/RNBugsnag.m#L49:L55).

**Comment by mmzoo** [comment]
Thank you. If you cannot reproduce it, it must be my setup. Closing for now.
