### ISSUE TITLE
iOS - Installation

### ISSUE THREAD

**Issue by jrm2k6** [SudoPlz/react-native-bugsnag#14]
After installing the library through CocoaPod, and when I try to import it, the build fails because of 
`#import <RNBugsnag/RNBugsnag.h>` in AppDelegate.m.

Any idea if I need extra steps? I have just been following the Readme.

**Comment by SudoPlz** [comment]
Ok would you mind giving the following steps a try:
1. Clear everything from your target `Framework Search paths` so that it becomes like this:
   ![screen shot 2016-08-24 at 18 44 44](https://cloud.githubusercontent.com/assets/3070948/17937492/f66a55fe-6a2a-11e6-8969-21da4ba2e738.png)
2. Then make sure your `Header Search Paths` look something like this:
   ![screen shot 2016-08-24 at 18 44 26](https://cloud.githubusercontent.com/assets/3070948/17937514/0a5eadb2-6a2b-11e6-8ac1-048db79f7844.png)

Let me know if any of the above helped you.

**Comment by jrm2k6** [comment]
I do have that. It seems that it still fails with atal error: 'RNBugsnag/RNBugsnag.h' file not found

**Comment by SudoPlz** [comment]
Gee that seems to be another one of those documentation errors of mine.

Can you try using `#import "RNBugsnag.h"` instead of `#import <RNBugsnag/RNBugsnag.h>` ?

A couple of days ago we used `Carthage` instead of `Cocoapods` and that line was left in the docs unchanged. 

Also if any of those errors take place again, you could check the `Example` project. It is a working version of the library so the code on that works.

**Comment by jrm2k6** [comment]
I still get an build issue sadly 

```
ld: warning: directory not found for option '-L/Users/jrm2k6/Library/Developer/Xcode/DerivedData/curologycompanion-chnpnpbjqwqqllabptgvlsivgnpc/Build/Products/Debug-iphonesimulator/Bugsnag'
ld: warning: directory not found for option '-L/Users/jrm2k6/Library/Developer/Xcode/DerivedData/curologycompanion-chnpnpbjqwqqllabptgvlsivgnpc/Build/Products/Debug-iphonesimulator/KSCrash'
ld: library not found for -lBugsnag
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by SudoPlz** [comment]
What this error is saying is that somewhere either on the project settings or the target settings there's a string targeting a directory called KSCrash. Can you search all the different settings of your target and your project for the string `KSCrash` ?

**Comment by jrm2k6** [comment]
The only thing I found so far is:
![screen shot 2016-09-13 at 10 34 57 am](https://cloud.githubusercontent.com/assets/1088099/18484560/d42b9200-799d-11e6-8e59-82bc0916d448.png)

It is also referenced in the Header Search Paths in my Build Settings options

![screen shot 2016-09-13 at 10 37 53 am](https://cloud.githubusercontent.com/assets/1088099/18484647/2a0e87ea-799e-11e6-9489-9eed78498a1c.png)

**Comment by SudoPlz** [comment]
If its referenced in your Library Search Paths, try removing them from there and let me know if it works like [so](http://stackoverflow.com/questions/9458739/ld-warning-directory-not-found-for-option).

**Comment by jrm2k6** [comment]
Oh I meant, Header Search Path. Trying to work on it right now.

I am kind of running out of ideas though, I feel like I have the same config as what you told me to have. Header Search Path contains a reference to bugsnag, and Framework Search Path is empty.

It says ld: framework not found RNBugsnag
clang: error: linker command failed with exit code 1 (use -v to see invocation)

SO it looks like the message changed.

**Comment by dwilt** [comment]
I'm having this issue as well: 
![image](https://cloud.githubusercontent.com/assets/1065539/18601217/67e26904-7c16-11e6-9a70-19df3b74da51.png)

I first ran npm install, then used Cocoa Pods to install. All worked well so far. Then updated my `AppDelegate.m` and am seeing the above which I'm assuming is the same boat that @jrm2k6 is in.

**Comment by dwilt** [comment]
I'm a total newb to Xcode and stuff but when I've installed other libraries into my project (and I've done a lot of them at this point), I usually have to update those `Header Search Paths` which you mentioned but I also usually have to link up some library under "Linked Libraries and Frameworks":

![image](https://cloud.githubusercontent.com/assets/1065539/18601276/d149907a-7c16-11e6-990d-6526dcdb2d6f.png)

Not saying that's required here but it's usually involved. It sounds like Ap

**Comment by SudoPlz** [comment]
This commit should totally fix all your troubles: 
https://github.com/SudoPlz/react-native-bugsnag/commit/4a00a0da1674c738af4b592a96982bbbaa665961

Please update your project (and use the `new` keyword when initializing Bugsnag from now on). Hopefully you won't have any more troubles now.

**Comment by dwilt** [comment]
@SudoPlz thanks for this commit. I ran `rnpm install react-native-bugsnag` and it says it successfully linked my projects:

![image](https://cloud.githubusercontent.com/assets/1065539/18609524/02992e40-7cb9-11e6-846d-0372ff77f15b.png)

But now I'm getting this build error in Xcode when trying to compile:

![image](https://cloud.githubusercontent.com/assets/1065539/18609529/0d65c356-7cb9-11e6-901c-fd45c00e52b7.png)

I see that the `RNBugsnag.framework` file is red and it isn't in my iOS folder. If I "Show in Finder" it, Finder doesn't open. When I view any of the files next to it (such as `libPods-GreatJonesStreetTests.a` which is highlighted in the below image), I can view those fine.

![image](https://cloud.githubusercontent.com/assets/1065539/18609536/5093c394-7cb9-11e6-86dc-8909a1fc5026.png)

So my guess is that the linking isn't actually copying the `.framework` file over correctly. Please advise as this is holding up our next release. Thanks so much for your help.

**Comment by SudoPlz** [comment]
This error is exactly what this commit solves. Just delete the .framework file manually and you should be ok.
The reason you still get this error is because your react native module was not updated by npm.

**Comment by dwilt** [comment]
Got it, thanks. Yea, I deleted it from Xcode and it seems to be working fine. I'm initializing the plugin but I'm still not seeing any error data show up. I ran the steps on your [iOS installation](https://github.com/SudoPlz/react-native-bugsnag/wiki/Step-3:-Configuring-the-iOS-project-%28if-needed%29) but I can't seem to get an error to report in my app in Bugsnag. It just says:

![image](https://cloud.githubusercontent.com/assets/1065539/18610005/14c28894-7cc5-11e6-9519-30bbc5816f48.png)

Any ideas?

**Comment by dwilt** [comment]
I can see this in the Xcode console log: 

``` bash
INFO : KSCrash.m (323): -[KSCrash sendAllReportsWithCompletion:]: Sending 1 crash reports
2016-09-17 10:55:51.365516 GreatJonesStreet[44209:1677505] [] tcp_connection_create_with_endpoint_and_parameters 8 notify.bugsnag.com 443
```

and 

```
2016-09-17 10:55:52.486 GreatJonesStreet[44209:1677579] Bugsnag reports sent.
```

**Comment by SudoPlz** [comment]
Ok this seems to be a problem with [the bugsnag iOS sdk itself](https://github.com/bugsnag/bugsnag-cocoa), and thus out of the scope of this react-native-module.

I think you should open an issue there or [contact the support team.](https://docs.bugsnag.com/platforms/ios-objc/support/)

I must admit though I've never ever seen it before.
Does the example project work for you?

Quick question, is the project of bugsnag dashboard of type `javascript`?

**Comment by dwilt** [comment]
Yes, it's a project type of Javascript in Bugsnag. I had an iOS one setup first and thought maybe that was the issue so I created a JS one then updated the keys in my Xcode to the JS project to see if it worked but still nothing.

I'll try out the example project and if that doesn't work, I'll come back here and we can figure out what to do next (most likely post an issue with Bugsnag themselves)

**Comment by jrm2k6** [comment]
@dwilt, @SudoPlz I still have the same issue, even when the package is updated to 1.0.0.
I am a newbie with xcode so I tried to remove the DerivedData content and clean the project several times. It still fails to build.

![screen shot 2016-09-20 at 10 34 53 am](https://cloud.githubusercontent.com/assets/1088099/18681701/0f33b280-7f1e-11e6-8ecc-5fc3aef448cc.png)

Do I still need to add RNBugsnag to the list of Header Search Paths or should I remove it? (it is still in there so far)

**Comment by dwilt** [comment]
@jrm2k6 did you make a feature branch to add this stuff in? What I would suggest doing would be to start from scratch before you started trying to integrate and then just run the `rnpm install`. That got me pretty far - granted I'm still busted - but it sounds like an issue with Bugsnag now. Still have to test the example project..

**Comment by SudoPlz** [comment]
@jrm2k6 It seems to me as if the pod is not installed. But even if thats not the case, would you be kind enough to start from scratch please:
1. Go to `node_modules` and delete the whole `react-native-bugsnag` directory.
2. Go to the `ios` directory and delete the `.xcworkspace` file, the `Pods` dir, and the `Podfile.lock` if theres one.

Then start from scratch.

1) `rnpm install react-native-bugsnag` 
2) go to the ios dir and `pod install` (provided you have already created the right Podfile within that dir`

and basically follow the guide as it is. I know those are steps you might have tried but this HAS to be the cause of your problems.

**Comment by jrm2k6** [comment]
Damn, looks like that was it. I swear to god I did this though but well, Xcode confuses me a lot!
Thanks a lot for your help!

**Comment by dwilt** [comment]
@jrm2k6 can you confirm that reports are actually showing up in Bugsnag?

**Comment by jrm2k6** [comment]
@dwilt I can't right now as I have some new issues with my signing certificates, meaning I cannot even install my app on my iphone emulator. I am just testing my app on a real Android device for now.

**Comment by SudoPlz** [comment]
@jrm2k6 I'm so glad that was it. Happens all the time, I'm familiar with Xcode but sometimes deleting everything and starting from scratch seems SO much faster to me.

**Comment by dwilt** [comment]
I'm in a similar boat right now @jrm2k6. It's a real fucking blast. Actually, if you'd like to screenshare, maybe we could help each other out. email me a google hangout if you're interested: dwilt4rville@gmail.com

**Comment by jrm2k6** [comment]
@dwilt I cannot screenshare today sadly. I know I was able to see reports on Bugsnag from the Android side.

**Comment by dwilt** [comment]
Followed my own advice. Deleted my feature branch that I was trying to install in, started from scratch and everything seems to be working.

**Comment by SudoPlz** [comment]
Fantastic!
