### ISSUE TITLE
Uploaded source maps dont help to de-obfuscate

### ISSUE THREAD

**Issue by UlfR** [SudoPlz/react-native-bugsnag#16]
Hi, @SudoPlz,

could you describe which params you use to create source map and to upload them to bugsnag?

I`ve tried to upload with minifiedUrl=index.android.bundle, minifiedUrl=/index.android.bundle, minifiedUrl=index.android.jsbundle, but no one helps to de-obfuscate stacktrace.
 I see in bugsnag traces only like this:
 index.android.bundle:1335 ReactJS.value
    index.android.bundle:536 ReactJS.c
    index.android.bundle:1555 ReactJS.action
    index.android.bundle:1555 ReactJS.<unknown>
    index.android.bundle:69 ReactJS.value
    index.android.bundle:69 ReactJS.<unknown>
    index.android.bundle:69 ReactJS.y
    index.android.bundle:69 ReactJS.value

**Comment by SudoPlz** [comment]
What about the first line of the error?
Do you get a de-obfuscated error on the first line in bugsnag dashboard?

Also about busgnag errors or advices you should talk to @kattrali he helped me set up source maps..!

**Comment by UlfR** [comment]
If you mean error text than it is de-obfuscated, like that:

"java.lang.Error index.android.bundle:1335
Can't find variable: XXXX"

**Comment by SudoPlz** [comment]
Here is a screenshot of the exact Postman call I used 
![screen shot 2016-09-17 at 03 42 04](https://cloud.githubusercontent.com/assets/3070948/18604747/f4461874-7c88-11e6-9116-c41216771fdd.png)

(Of course I selected a `sourceMap` file AND a `minifiedFile` file that cannot be seen on the screenshot.)

I only used [this page here](https://docs.bugsnag.com/api/js-source-map-upload/#uploading-source-maps) as my guide.
I hope this helps.

**Comment by morelazers** [comment]
Hi, what is stored at the boxcloud URL in your screenshot here @SudoPlz?

I have hosted my main.jsbundle and used the URL of that but it is not working.
