### ISSUE TITLE
Captures crashes?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [SudoPlz/react-native-bugsnag#17]
Does this module capture crashes?

**Comment by SudoPlz** [comment]
What do you mean capture. When a crash occurs this library will report it to the dashboard.
In that sense yes it does capture crashes but it does _NOT_ suppress them like if you had a try catch block.

**Comment by inetfuture** [comment]
Hi,  @SudoPlz , first, I want to thank your great work.

I just finished integration, manually report errors works fine, auto report unhandled exception on dev mode works fine too, but auto report unhandled exception on release mode does not work, both iOS and Android.

I dig into iOS a little, find that bugsnag sdk store exception information on crash into a crash report file, then it will try to read and send it to server on next start. But it fails to send because a crash report file decode error, here is related log I saw in Xcode:

```
ERROR: KSSysCtl.c (228): _Bool kssysctl_getProcessInfo(const int, struct kinfo_proc *const): Could not get the name for process 11372: Operation not permitted 
ERROR: KSCrashReportStore.m (422): -[KSCrashReportStore readReport:error:]: Error decoding JSON data from /var/mobile/Containers/Data/Application/197B0D17-0D3D-405D-928D-3F8D7A8FAB1E/Library/Caches/KSCrashReports/BBPv2.5.5/BBPv2.5.5-CrashReport-8FEE8103-66FE-4451-A315-A6C4032C8CAE.json: Error Domain=KSJSONCodecObjC Code=0 "Invalid character (offset 6218)" UserInfo={NSLocalizedDescription=Invalid character (offset 6218)} 
ERROR: KSCrashReportStore.m (207): -[KSCrashReportStore reportWithID:]: Encountered error loading crash report 8FEE8103-66FE-4451-A315-A6C4032C8CAE: Error Domain=KSJSONCodecObjC Code=0 "Invalid character (offset 6218)" UserInfo={NSLocalizedDescription=Invalid character (offset 6218)} 
INFO : KSCrash.m (341): -[KSCrash sendAllReportsWithCompletion:]: Sending 1 crash reports
2016-09-21 13:41:48.625 ToBusinessPhone[11373:3539487] Bugsnag reports sent.
```

I tried to add breakpoint right before the decoding, manually decoded the `jsonData` as string, show this:

```
{
    "report": {
        "version": {
            "major": 3,
            "minor": 0
        },
        "id": "F8583382-A094-421C-A97F-4B3C340DC4CB",
        "process_name": "ToBusinessPhone",
        "timestamp": 1474443954,
        "type": "standard"
    },
    "binary_images": [
        {
            "image_addr": 4295540736,
            "image_vmaddr": 4294967296,
            "image_size": 1736704,
            "name": "/var/containers/Bundle/Application/FCA3390C-AA7F-4DD2-BD13-A33DC7FDFD4D/ToBusinessPhone.app/ToBusinessPhone",
            "uuid": "D1571A6A-0F41-3E13-BCC6-0F4F42EBE7E1",
            "cpu_type": 16777228,
            "cpu_subtype": 0
        },
        {
            "image_addr": 4300144640,
            "image_vmaddr": 0,
            "image_size": 32768,
            "name": "/Developer/usr/lib/libBacktraceRecording.dylib",
            "uuid": "5B9555FE-8B75-3091-A558-9ED6E26C2B80",
            "cpu_type": 16777228,
            "cpu_subtype": 0
        },
        {
            "image_addr": 4300226560,
            "image_vmaddr": 0,
            "image_size": 32768,
            "name": "/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib",
            "uuid": "68749631-20DC-3938-9A37-3CD70F6B929D",
            "cpu_type": 16777228,
            "cpu_subtype": 0
        },
        {
            "image_addr": 4300324864,
            "image_vmaddr": 0,
            "image_size": 196608,
            "name": "/private/var/containers/Bundle/Application/FCA3390C-AA7F-4DD2-BD13-A33DC7FDFD4D/ToBusinessPhone.app/Frameworks/Bugsnag.framework/Bugsnag",
            "uuid": "770E20E6-B883-3563-B69B-741ADDA942E4",
            "cpu_type": 16777228,
            "cpu_subtype": 0
        },
        {
            "image_addr": 6488424448,
            "image_vmaddr": 6442631168,
            "image_size": 339968,
            "name": "/usr/lib/libc++.1.dylib",
            "uuid": "9EC0D9DC-F728-3495-82C2-6A7DA72F0364",
            "cpu_type": 16777228,
            "cpu_subtype": 0
        },
        {
            "image_addr": 6497697792,
            "image_vmaddr": 6451904512,
            "image_size": 73728,
            "name": "/usr/lib/libz.1.dylib",
            "uuid": "8FCB56AD-FDC1-3E95-9358-2266B1E4AC18",
            "cpu_type": 16777228,
            "cpu_subtype": 0
        },
        {
            "image_addr": 6508314624,
            "image_vmaddr": 6462521344,
            "image_size": 2551808,
            "name": "/System/Library/Frameworks/Foundation.framework/Foundation",
            "uuid": "7CF4EDF7-81CB-3043-8B81-2DED8716CD95",
            "cpu_type": 16777228,
            "cpu_subtype": 0
        },
        {
            "image_addr": 6488899584,
            "image_vmaddr": 6443106304,
            "image_size": 3592192,
            "name": "/usr/lib/libobjc.A.dylib",
            "uuid": "939F3920-2290-3F2D-A285-8E676E4191EF",
            "cpu_type": 16777228,
            "cpu_subtype": 0
        },
        {
            "image_addr": 6488408064,
            "image_vmaddr": 6442614784,
```

Looks like the file is incomplete.

Any idea what could be wrong?

Thanks

**Comment by inetfuture** [comment]
The on purpose error is created like this:

```
  _onPressTestCrashReporting = () => {
    throw new Error(`Test crash reporting at ${new Date()}`);
  }
```

**Comment by inetfuture** [comment]
I find that I was using 4.1.0 Bugsnag sdk due to cocoapods spec repo outdated, just upgraded to the latest 5.5.0, but now build fails with error `/Users/aaron/wp/To-Business-Phone/node_modules/react-native-bugsnag/ios/RNBugsnag/RNBugsnag.m:3:9: 'Bugsnag/Bugsnag.h' file not found`

**Comment by inetfuture** [comment]
@SudoPlz Could you please confirm that this library can work with bugsnag 5.5.0? This is driving me nuts, I have no idea what went wrong.

**Comment by SudoPlz** [comment]
For me usually a `pod install` with the default `pod Bugsnag` does the trick, but I'll have to update to 5.5.0 and see if it works for me too.

**Comment by inetfuture** [comment]
ok, what version are you using now?

**Comment by SudoPlz** [comment]
I'm using 
`Bugsnag (5.4.2)`
`KSCrash (1.6.4)`

Was your problem not providing a Bugsnag id within the `Info.plist` by any chance?

**Comment by inetfuture** [comment]
> Was your problem not providing a Bugsnag id within the Info.plist by any chance?

no, manually call `notify` works.

**Comment by inetfuture** [comment]
I fixed the `file not found` error.

Now I can see `crash report send` log in Xcode without any error, but those crash does not show up in bugsnag dashboard.

In dev mode, it works, but not in production mode.

**Comment by inetfuture** [comment]
> I fixed the file not found error.

The trick is to remove `use_framework!` from Podfile, although I still don't understand why.

> Now I can see crash report send log in Xcode without any error, but those crash does not show up in bugsnag dashboard.

Now it works, but I don't know why it fails several hours ago.

**Comment by SudoPlz** [comment]
So weird.. How did `use_framework!` end up in your Podfile, were you using it before installing RNBugsnag? I'm glad you found a solution!

**Comment by inetfuture** [comment]
no, I thought since I have some swift code, so I maybe keep it on as well, I didn't think that it would break something. Weird thing is, 4.1.0 compiles, but breaks on 5.0.0+, and 4.1.0 has bug on loading crash report file, lucky me...

Android still is not working, I'm trying to figure out why.

**Comment by inetfuture** [comment]
Below is the screenshot of charles recorded bugsnag api call on android crash(happens right after crash, not like ios on next start), it says the request failed, my guess is the report process is killed by OS

![screen shot 2016-09-22 at 21 14 19](https://cloud.githubusercontent.com/assets/1363189/18749524/e2b10b3e-8109-11e6-9fd4-f2a8ad8b8f2e.png)

**Comment by inetfuture** [comment]
And `adb logcat` shows nothing related to Bugsnag

**Comment by SudoPlz** [comment]
That's such a weird bug, have you opened an issue to their repos? Here is [their iOS repo](https://github.com/bugsnag/bugsnag-cocoa) and this is[ their android repo](https://github.com/bugsnag/bugsnag-android).

**Comment by inetfuture** [comment]
About android reporting, I'm waiting for Bugsnag's response.

Now I'm testing the sourcemap uploading, sadly, not working...

Here is the command I used to create sourcemap and upload to bugsnag:

```
node ./node_modules/react-native/local-cli/cli.js bundle \
    --platform ios \
    --entry-file index.ios.js \
    --dev false \
    --reset-cache true \
    --bundle-output "/Users/aaron/wp/To-Business-Phone/ios/build/main.jsbundle" \
    --assets-dest /tmp \
    --sourcemap-output "/Users/aaron/wp/To-Business-Phone/ios/build/sourcemap.js"
curl https://upload.bugsnag.com \
    --fail \
    --retry 1 \
    -F "apiKey=****" \
    -F "appVersion=ios-2.5.5-2016-09-23T02:13:27.000Z" \
    -F "minifiedUrl=main.jsbundle" \
    -F "minifiedFile=@/Users/aaron/wp/To-Business-Phone/ios/build/main.jsbundle" \
    -F "sourceMap=@/Users/aaron/wp/To-Business-Phone/ios/build/sourcemap.js" \
    -F "overwrite=true"
```

Inside app, I use bugsnag api to set the app version as `ios-2.5.5-2016-09-23T02:13:27.000Z`, and error report in dashboard is showing correctly 

Below is the screenshot of the error report:

![screen shot 2016-09-23 at 11 17 51](https://cloud.githubusercontent.com/assets/1363189/18773205/7a67c1b4-817f-11e6-976c-03e99b6fefa3.png)

**Comment by SudoPlz** [comment]
@kattrali [(Delisa Mason)](www.delisa.me) is the person to talk to about creating a sourcemap and uploading it. He guided me when I first did it ([this is the discussion we had](https://gitter.im/SudoPlz/react-native-bugsnag)) on July 05 2016, 20:37.

**Comment by yabinliu** [comment]
@inetfuture have you solved  it for android crash?

**Comment by inetfuture** [comment]
> @inetfuture have you solved it for android crash?

We have switched to bugsnag's official library bugsnag-react-native

**Comment by yabinliu** [comment]
@inetfuture bugsnag-react-native on release mode does it work?

**Comment by inetfuture** [comment]
According to my teammates, it works, but I did not test it by myself. I think you should try, at least, this project has been deprecated in fave of the official one.
