### ISSUE TITLE
Android documentation update

### ISSUE THREAD

**Issue by dwilt** [SudoPlz/react-native-bugsnag#18]
I think the documentation for Android installation has some problems:

Step 2 says.. 

> Go to your app/settings.gradle and add the following line in the end: 

There is no `settings.gradle` inside of the app folder. There is the `build.gradle` which has that dependencies object just like that at the end..

Step 3 says..

> Go to your manifest.xml and add the following line within the application tag replacing YOUR_API_KEY:

I think the file is `AndroidManifest.xml`, correct?

**Comment by SudoPlz** [comment]
You're absolutely right. Just fixed it. Thank you.
