### ISSUE TITLE
`new BugSnag()` is a little weird IMHO

### ISSUE THREAD

**Issue by tuckerconnelly** [SudoPlz/react-native-bugsnag#24]
Why not do it like nodejs and use the required module as the singleton?

Or maybe, create a Provider (like redux does), and send the `bugsnag` object down the `context`

Thanks BTW, this looks miles better than Sentry :)

**Comment by SudoPlz** [comment]
Would you be kind enough to open a pull request about all of you're thoughts? I have seriously no time during the past weeks to get my hands on this, but I'll be more than happy to accept pull requests.

**Comment by SunnyGurnani** [comment]
I checked its actually creating multiple Objects of Bugsnag so if you import RNBugSnag into multiple files and call new BugSnag() it actually creates new object instead of using Signleton.

**Comment by SunnyGurnani** [comment]
https://github.com/SudoPlz/react-native-bugsnag/pull/25 Here is the fix

**Comment by SudoPlz** [comment]
Sure I'll take a look at it and let you know, thank you! Closing for now!
