### ISSUE TITLE
Build failed : redefinition of module Bugsnag on Xcode 7.3

### ISSUE THREAD

**Issue by yboulkaid** [SudoPlz/react-native-bugsnag#5]
When following the installation instructions the xcode build ultimately fails because of : 

```
.../rn-bugsnag-example-app/ios/Carthage/Checkouts/bugsnag-cocoa/OSX/module.modulemap:1:8: Redefinition of module 'Bugsnag'
```

This seems to be an issue that people started seeing with Xcode 7.3.

At first I thought this was related to the Bugsnag native library but I failed to reproduce the problem with native code. This seems to be related to the react-native-bugsnag library itself.

Going into the checked out `Bugsnag` Carthage package and deleting the `OSX` and `TvOS` folders solves the issue as this removes the faulty `module.modulemap` files that define the `Bugsnag` modules. Maybe the library is loading all the modulemap files when it should only be loading the ones specific to a certain build ?

I created an example app to reproduce the issue : https://github.com/yboulkaid/rn-bugsnag-example-app/

**Comment by SudoPlz** [comment]
Just use Cocoapods man, Carthage is a bit hard to get used to. I updated the docs to get users to use Cocoapods instead.
