### ISSUE TITLE
NativeBugsnag.notify is not a function

### ISSUE THREAD

**Issue by jrm2k6** [SudoPlz/react-native-bugsnag#8]
I am trying to manually dispatch an error to see if my config is correct.
This is what I have:

```
componentDidMount() {
    const { user } = this.props;
    if (user) {
      Bugsnag();
      Bugsnag().notify("RANDOM EXCEPTION", "THIS IS A TEST", "error");
    }
  }
```

But it shows a warning saying that NativeBugsnag.notify is not a function.

My diff after installation of the package is:

```
@@ -133,6 +133,7 @@ repositories {
 }

 dependencies {
+    compile project(':react-native-bugsnag')
     compile project(':react-native-dialogs')
     compile project(':ReactNativeBarcodescanner')
     compile fileTree(dir: "libs", include: ["*.jar"])

--- a/Inventology/android/app/src/main/AndroidManifest.xml
+++ b/Inventology/android/app/src/main/AndroidManifest.xml
@@ -25,6 +25,7 @@
         </intent-filter>
       </activity>
       <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
+      <meta-data android:name="com.bugsnag.android.API_KEY" android:value="MYKEYINHERE"/>
     </application>

 </manifest>

--- a/Inventology/android/app/src/main/java/com/inventology/MainActivity.java
+++ b/Inventology/android/app/src/main/java/com/inventology/MainActivity.java
@@ -1,6 +1,7 @@
 package com.inventology;

 import com.facebook.react.ReactActivity;
+import com.pintersudoplz.rnbugsnag.RNBugsnagPackage;
 import com.aakashns.reactnativedialogs.ReactNativeDialogsPackage;
 import com.eguma.barcodescanner.BarcodeScanner;
 import com.facebook.react.ReactPackage;
@@ -38,6 +39,7 @@ public class MainActivity extends ReactActivity {
     protected List<ReactPackage> getPackages() {
         return Arrays.<ReactPackage>asList(
             new MainReactPackage(),
+            new RNBugsnagPackage(),
             new ReactNativeDialogsPackage(),

+include ':react-native-bugsnag'
+project(':react-native-bugsnag').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-bugsnag/android')

```

Any idea what I am doing wrong?
Also, I was trying to dispatch an error by trying to access and non-declared variable but it also didn't work out, I cannot see the error in my Bugsnag dashboard.

**Comment by SudoPlz** [comment]
I will look into this later tonight, please hang on.

**Comment by jrm2k6** [comment]
Sure thing! Thanks

**Comment by SudoPlz** [comment]
Ok that was my bad, some code went missing into the abyss.

I just commited this: https://github.com/SudoPlz/react-native-bugsnag/commit/ae0f3212cd1b9d3bd18036d2135c427487cac17b . Just `git pull` and it should fix your problem hopefully. Let me know if it works, I did not really test this part on a phone yet.

Thank you.

**Comment by jrm2k6** [comment]
@SudoPlz Yeah, notify now works from master. I am just wondering why it doesn't dispatch an error when I get an exception in my javascript code, for example, attempting to access a property not existing on an object (where I can see a warning on my device)

**Comment by jrm2k6** [comment]
Quick ping.

**Comment by SudoPlz** [comment]
Sorry for the delay, I was away.

Are you trying to see an error when on development mode?

What does the `__DEV__` print out if you run `console.log(__DEV__);` ?

You could just call `Bugsnag().setSuppressDebugOnDev(false);` if you specifically wish to receive reports on DEV mode as well.

**Comment by jrm2k6** [comment]
Yes, I am trying to make sure that JS errors are dispatched correctly.

```
componentDidMount() {
    const { user } = this.props;
    Bugsnag().setIdentifier("1", "jeremy.dagorn@gmail.com", "Jeremy Dagorn");
    Bugsnag().setSuppressDebugOnDev(false);
    console.log(__DEV__);
    console.log(this.pros.lol);
  }
```

I am in dev mode, but I am still not seeing exceptions sent from my javascript code to Bugsnag.

**Comment by SudoPlz** [comment]
Can you try to `throw new Error("test");` after the console log?

**Comment by SudoPlz** [comment]
Apart from this code have you set the bugsnag project id in the native part of your project?

**Comment by jrm2k6** [comment]
@SudoPlz Yes, I do have the bugsnag project id setup. I am able to see exceptions on my Bugsnag dashboard when using the notify function.

Throwing an error does not dispatch anything to Bugsnag. I just see the warning (orange/yellow box) in my RN app though.

**Comment by SudoPlz** [comment]
That sounds very very strange,
could you go to `<project_dir>/node_modules/react-native-bugsnag/lib/RNBugsnag.js` and add this line `console.log("Error: "+error);` below the `async wrapGlobalHandler(error, isFatal){` line?

I want to test if `wrapGlobalHandler` gets called when you throw an Error in javascript. 
I never had such an error happen to me.

Also play with the values within that function, to see what might have gone wrong, I'd also test the `reportExceptionPromise` result.

**Comment by jrm2k6** [comment]
Alright, will try to work on this later this weekend!
Thanks for the help

**Comment by jrm2k6** [comment]
**Edit: This is valid for "react-native": "0.32.0" (new project I am working on).**
So, I have installed the newest version and was not able to get my javascript exception to be sent to bugsnag. After looking around in the code, I found out that even if instantiate the Bugsnag instance with {suppressDevErrors:true}, it will be ignored as it seems that: 

```
if((!!props && props.suppressDevErrors===true) || (__DEV__===true)) {
      this.setSuppressDebugOnDev(true);
    }
```

will always be executed as we don't necessarily have control over the value of **DEV** right?

I was able to dispatch my exception to Bugsnag by modifying this.
I am also wondering what is the use case for having a timeout handler instead of just the notify exception promise. I am referring to this 
`Promise.race([reportExceptionPromise, timeoutPromise])   //whatever finishes first`?

**React Native 0.25.1:**

I did the same process as for what I described earlier. In that case, it seems that the `wrapGlobalHandler` is not called when throwing a JS exception. I will try to go deeper and see why!

Edit: So I investigated a bit further.
I have a first component A, that triggers an async request returning a promise in a componentDidMount. In the same component, I have a componentWillUpdate that will push a new component B to the top of the stack of my navigator. I am originally setting my Bugsnag instance in the componentDidMount of the component B, followed by a `throw new Error('error');`. It looks like the promise handler of component A is still catching this error and failed with a 'Unhandled rejection Error: error'. I am not sure why or how to fix it yet but it has not really anything to do with this library.

**Comment by SudoPlz** [comment]
Ah such a great analysis of the situation. 

About the `timeoutPromise` theres a specific time window that we want to wait for the `reportExceptionPromise` promise to be successful. If time passes and we get nothing then `timeoutPromise` wins the 'race' and thus dispatches first.

About the `__DEV__` flag, this was a user request, but I believe it has caused more trouble than good. 
I will change that tonight in the following way. The library will always be disabled on dev UNLESS the user explicitly specifies the `suppressDevErrors` to `false`.

Update: This should do it. https://github.com/SudoPlz/react-native-bugsnag/commit/2cb20eae68b4f5180ce6f4a305aa70882f63b48d

**Comment by jrm2k6** [comment]
Thanks! Perfect for the solution about suppressDevErrors!
I have just open another issue about installing on iOS if you mind checking. This issue is already close so we are good to go!
