### ISSUE TITLE
Need better instructions for how to set up project in bugsnag

### ISSUE THREAD

**Issue by cayblood** [SudoPlz/react-native-bugsnag#9]
It's not clear whether I need to create three separate projects to use bugsnag with react native or one. Do I need to create separate iOS, android and javascript projects in bugsnag, or can I combine all these into one project?

**Comment by SudoPlz** [comment]
That is a bugsnag question really.

To answer your question, you only need 1 bugsnag project of type **JavaScript** on their website dashboard.
So you just combine then all to one.

Now if you really want to you could use two projects of type **JavaScript** one for ios and one for java, but in all my projects i use one for all.

The bugsnag team told me that they are working on a project of type **hybrid** with better stacktrace recognition, but apparently it's not yet ready

**Comment by cayblood** [comment]
Thanks for your quick response! If you really want to make this tool more developer-friendly, I think providing insights just like you shared here in the readme instructions would be tremendously helpful, for what it's worth.

So are you saying we will currently miss out on some stacktrace parsing features when native errors are thrown if we use a javascript project in bugsnag instead of an ios or android project? I'd certainly like to consolidate it all under one project if it works alright.

**Comment by SudoPlz** [comment]
Please modify the read me I will accept the pull request.

Yes combine them all in one project.
The only trouble I currently have with bugsnag even though the team told me they will fix that is that even though all the native stacktraces work well, the JavaScript stacktrace appears fine all of it but the real file name from where the error originated does not show up.
I'm waiting for them to fix this.
